### ISSUE TITLE
AttributeError: 'list' object has no attribute 'data'

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/relay#321]
here's an error from running the end2end tests:
 https://circleci.com/gh/schmir-forks/end2end/27?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

relay server version: 0.7.1.dev1+ge65b416

```
parity          | 2019-09-10T11:20:52.654408286Z 2019-09-10 11:20:52 UTC Transaction mined (hash 0xc76292819c170ac91290e43908eacf7edba78240a164b063b641183c080d4423)
index_1         | 2019-09-10T11:20:52.665948475Z INFO:ethindex.pgimport:got 12 events in 7 out of 11 blocks (63 -> 73)
index_1         | 2019-09-10T11:20:52.704448839Z INFO:ethindex.pgimport:got 13 events in 7 out of 11 blocks (64 -> 74)
index_1         | 2019-09-10T11:20:52.733911171Z INFO:ethindex.pgimport:already synced up to latest block 74
relay           | 2019-09-10T11:20:53.387304823Z 2019-09-10 11:20:53,386[DEBUG] proxy: new entries for filter Filter for 0x5: [AttributeDict({'args': AttributeDict({'_creditor': '0xB018a4F46c263BbEEbd94F1085A170b6359E03a6', '_debtor': '0x221005788dB312026509FF341ade826C07e82B33', '_creditlineGiven': 3000000, '_creditlineReceived': 4000000, '_interestRateGiven': 1000, '_interestRateReceived': 1000, '_isFrozen': False}), 'event': 'TrustlineUpdate', 'logIndex': 0, 'transactionIndex': 0, 'transactionHash': HexBytes('0xc76292819c170ac91290e43908eacf7edba78240a164b063b641183c080d4423'), 'address': '0x492934308E98b590A626666B703A6dDf2120e85e', 'blockHash': HexBytes('0xd80e9782b31c2b5016c76b73bb3e95c0c9e80d398626afa1f77cd52a9a842d56'), 'blockNumber': 74})]
relay           | 2019-09-10T11:20:53.398083541Z 2019-09-10 11:20:53,395[DEBUG] relay: Process trustline update event
relay           | 2019-09-10T11:20:53.427036685Z 2019-09-10 11:20:53,426[DEBUG] proxy: new entries for filter Filter for 0x7: [AttributeDict({'args': AttributeDict({'_creditor': '0xB018a4F46c263BbEEbd94F1085A170b6359E03a6', '_debtor': '0x221005788dB312026509FF341ade826C07e82B33', '_creditlineGiven': 3000000, '_creditlineReceived': 4000000, '_interestRateGiven': 1000, '_interestRateReceived': 1000, '_isFrozen': False}), 'event': 'TrustlineUpdateRequest', 'logIndex': 0, 'transactionIndex': 0, 'transactionHash': HexBytes('0x33f9a37d0696c437c665c39b17752567904a2125c5ba79745cd0028c7315dea5'), 'address': '0x492934308E98b590A626666B703A6dDf2120e85e', 'blockHash': HexBytes('0x0cadc68ed30a0e4d4ef9b323cc241cf673e681ea11de59869c17318dca7824b1'), 'blockNumber': 73})]
relay           | 2019-09-10T11:20:53.432178176Z 2019-09-10 11:20:53,431[DEBUG] relay: Process trustline request event
e2e             | 2019-09-10T11:20:54.658732815Z       #getExAddresses()
e2e             | 2019-09-10T11:20:54.660180767Z         ✓ should return array
e2e             | 2019-09-10T11:20:54.660823890Z       #getOrderbook()
e2e             | 2019-09-10T11:20:54.662056145Z         ✓ should return orderbook
e2e             | 2019-09-10T11:20:54.665146602Z       #makeOrder()
relay           | 2019-09-10T11:20:54.701161001Z 2019-09-10 11:20:54,698[ERROR] relay.api.app: Exception on /api/v1/exchange/orderbook [GET]
relay           | 2019-09-10T11:20:54.701202404Z Traceback (most recent call last):
relay           | 2019-09-10T11:20:54.701208058Z   File "/opt/relay/lib/python3.6/site-packages/flask_sockets.py", line 40, in __call__
relay           | 2019-09-10T11:20:54.701212305Z     handler, values = adapter.match()
relay           | 2019-09-10T11:20:54.701216207Z   File "/opt/relay/lib/python3.6/site-packages/werkzeug/routing.py", line 1799, in match
relay           | 2019-09-10T11:20:54.701219930Z     raise NotFound()
relay           | 2019-09-10T11:20:54.701223644Z werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
relay           | 2019-09-10T11:20:54.701227643Z 
relay           | 2019-09-10T11:20:54.701231483Z During handling of the above exception, another exception occurred:
relay           | 2019-09-10T11:20:54.701235291Z 
relay           | 2019-09-10T11:20:54.701238566Z Traceback (most recent call last):
relay           | 2019-09-10T11:20:54.701241914Z   File "/opt/relay/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
relay           | 2019-09-10T11:20:54.701245922Z     rv = self.dispatch_request()
relay           | 2019-09-10T11:20:54.701249610Z   File "/opt/relay/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
relay           | 2019-09-10T11:20:54.701253786Z     return self.view_functions[rule.endpoint](**req.view_args)
relay           | 2019-09-10T11:20:54.701257659Z   File "/opt/relay/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
relay           | 2019-09-10T11:20:54.701261540Z     resp = resource(*args, **kwargs)
relay           | 2019-09-10T11:20:54.701264641Z   File "/opt/relay/lib/python3.6/site-packages/flask/views.py", line 89, in view
relay           | 2019-09-10T11:20:54.701276185Z     return self.dispatch_request(*args, **kwargs)
relay           | 2019-09-10T11:20:54.701279959Z   File "/opt/relay/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
relay           | 2019-09-10T11:20:54.701284048Z     resp = meth(*args, **kwargs)
relay           | 2019-09-10T11:20:54.701287370Z   File "/opt/relay/lib/python3.6/site-packages/webargs/core.py", line 472, in wrapper
relay           | 2019-09-10T11:20:54.701291457Z     return func(*new_args, **kwargs)
relay           | 2019-09-10T11:20:54.701294926Z   File "/opt/relay/lib/python3.6/site-packages/relay/api/exchange/resources.py", line 60, in get
relay           | 2019-09-10T11:20:54.701299592Z     many=True,
relay           | 2019-09-10T11:20:54.701303692Z AttributeError: 'list' object has no attribute 'data'
e2e             | 2019-09-10T11:20:54.729912846Z (node:31) UnhandledPromiseRejectionWarning: Error: Error fetching http://relay:5000/api/v1/exchange/orderbook?baseTokenAddress=0xee35211C4D9126D520bBfeaf3cFee5FE7B86F221&quoteTokenAddress=0x492934308E98b590A626666B703A6dDf2120e85e | Status 500 | Internal Server Error
e2e             | 2019-09-10T11:20:54.729960544Z     at Object.<anonymous> (/clientlib/src/utils.ts:6:735)
e2e             | 2019-09-10T11:20:54.729966987Z     at step (/clientlib/src/utils.ts:1:40886)
e2e             | 2019-09-10T11:20:54.729987059Z     at Object.next (/clientlib/src/utils.ts:1:37924)
e2e             | 2019-09-10T11:20:54.729992307Z     at fulfilled (/clientlib/src/utils.ts:1:36427)
e2e             | 2019-09-10T11:20:54.729996481Z     at process._tickCallback (internal/process/next_tick.js:68:7)
e2e             | 2019-09-10T11:20:54.730000440Z (node:31) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
e2e             | 2019-09-10T11:20:54.730005106Z (node:31) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
e2e             | 2019-09-10T11:20:54.767823086Z         ✓ should make order (102ms)
e2e             | 2019-09-10T11:20:54.768281689Z       #getOrderByHash()
e2e             | 2019-09-10T11:20:54.853601694Z         ✓ should return order by its hash
e2e             | 2019-09-10T11:20:54.853935480Z       getOrders()
e2e             | 2019-09-10T11:20:55.023068701Z         ✓ should return 2 already created orders (45ms)
e2e             | 2019-09-10T11:20:55.096801303Z         ✓ should return only orders of specific user (73ms)
e2e             | 2019-09-10T11:20:55.168852228Z         ✓ should return one order (71ms)
e2e             | 2019-09-10T11:20:55.169965785Z       #prepTakeOrder()
e2e             | 2019-09-10T11:20:55.251953241Z         ✓ should prepare a fill order tx for latest order
e2e             | 2019-09-10T11:20:55.257103092Z       #confirm() - TL money <-> TL money
parity          | 2019-09-10T11:20:55.590955248Z 2019-09-10 11:20:55 UTC Imported #75 0x9c5e…a155 (1 txs, 0.15 Mgas, 0 ms, 1.25 KiB) + another 1 block(s) containing 1 tx(s)
parity          | 2019-09-10T11:20:55.590989788Z 2019-09-10 11:20:55 UTC Transaction mined (hash 0x5d35103d8f982f4e2adc982d11541fbe7bbbf867f798e743dc528c424949855b)
index_1         | 2019-09-10T11:20:55.684560812Z INFO:ethindex.pgimport:got 18 events in 8 out of 11 blocks (65 -> 75)
index_1         | 2019-09-10T11:20:55.721129334Z INFO:ethindex.pgimport:already synced up to latest block 75
relay           | 2019-09-10T11:20:56.063605827Z 2019-09-10 11:20:56,063[DEBUG] proxy: new entries for filter Filter for 0x0: [AttributeDict({'args': AttributeDict({'_from': '0xB018a4F46c263BbEEbd94F1085A170b6359E03a6', '_to': '0x221005788dB312026509FF341ade826C07e82B33', '_value': -5000}), 'event': 'BalanceUpdate', 'logIndex': 0, 'transactionIndex': 0, 'transactionHash': HexBytes('0x5d35103d8f982f4e2adc982d11541fbe7bbbf867f798e743dc528c424949855b'), 'address': '0xee35211C4D9126D520bBfeaf3cFee5FE7B86F221', 'blockHash': HexBytes('0x9c5ed44fd2de9cd8a9b1666838e584b621315ff69324c2eec35aefd3404fa155'), 'blockNumber': 75})]
relay           | 2019-09-10T11:20:56.253397009Z 2019-09-10 11:20:56,253[DEBUG] proxy: new entries for filter Filter for 0x4: [AttributeDict({'args': AttributeDict({'_from': '0x221005788dB312026509FF341ade826C07e82B33', '_to': '0xB018a4F46c263BbEEbd94F1085A170b6359E03a6', '_value': -5000}), 'event': 'BalanceUpdate', 'logIndex': 2, 'transactionIndex': 0, 'transactionHash': HexBytes('0x5d35103d8f982f4e2adc982d11541fbe7bbbf867f798e743dc528c424949855b'), 'address': '0x492934308E98b590A626666B703A6dDf2120e85e', 'blockHash': HexBytes('0x9c5ed44fd2de9cd8a9b1666838e584b621315ff69324c2eec35aefd3404fa155'), 'blockNumber': 75})]
relay           | 2019-09-10T11:20:56.449145145Z 2019-09-10 11:20:56,448[DEBUG] proxy: new entries for filter Filter for 0x6: [AttributeDict({'args': AttributeDict({'_from': '0x221005788dB312026509FF341ade826C07e82B33', '_to': '0xB018a4F46c263BbEEbd94F1085A170b6359E03a6', '_value': 5000, '_extraData': b''}), 'event': 'Transfer', 'logIndex': 3, 'transactionIndex': 0, 'transactionHash': HexBytes('0x5d35103d8f982f4e2adc982d11541fbe7bbbf867f798e743dc528c424949855b'), 'address': '0x492934308E98b590A626666B703A6dDf2120e85e', 'blockHash': HexBytes('0x9c5ed44fd2de9cd8a9b1666838e584b621315ff69324c2eec35aefd3404fa155'), 'blockNumber': 75})]
relay           | 2019-09-10T11:20:56.456948749Z 2019-09-10 11:20:56,456[DEBUG] proxy: new entries for filter Filter for 0x2: [AttributeDict({'args': AttributeDict({'_from': '0xB018a4F46c263BbEEbd94F1085A170b6359E03a6', '_to': '0x221005788dB312026509FF341ade826C07e82B33', '_value': 5000, '_extraData': b''}), 'event': 'Transfer', 'logIndex': 1, 'transactionIndex': 0, 'transactionHash': HexBytes('0x5d35103d8f982f4e2adc982d11541fbe7bbbf867f798e743dc528c424949855b'), 'address': '0xee35211C4D9126D520bBfeaf3cFee5FE7B86F221', 'blockHash': HexBytes('0x9c5ed44fd2de9cd8a9b1666838e584b621315ff69324c2eec35aefd3404fa155'), 'blockNumber': 75})]
relay           | 2019-09-10T11:20:56.483120532Z 2019-09-10 11:20:56,482[DEBUG] proxy: new entries for filter Filter for 0xc: [AttributeDict({'args': AttributeDict({'maker': '0xB018a4F46c263BbEEbd94F1085A170b6359E03a6', 'feeRecipient': '0x0000000000000000000000000000000000000000', 'tokens': b'\xe8\xe6E\x0c\xeb\x17\x93\xbe\xee:rj\n\x1f\xe1`"I\xd2\xc6 .3\xbe\x98;\x91\xa5PS\xd6\xaa', 'taker': '0x221005788dB312026509FF341ade826C07e82B33', 'makerToken': '0xee35211C4D9126D520bBfeaf3cFee5FE7B86F221', 'takerToken': '0x492934308E98b590A626666B703A6dDf2120e85e', 'filledMakerTokenAmount': 5000, 'filledTakerTokenAmount': 5000, 'paidMakerFee': 0, 'paidTakerFee': 0, 'orderHash': b'\xdb\x10\xeb\xf6\xd6+!X\xf2\x98\xc5l\xa4\xcf\x14HC4\x15x>\x93\xc8\xb0b\x8b\x00xfZ_B'}), 'event': 'LogFill', 'logIndex': 4, 'transactionIndex': 0, 'transactionHash': HexBytes('0x5d35103d8f982f4e2adc982d11541fbe7bbbf867f798e743dc528c424949855b'), 'address': '0x731a10897d267e19B34503aD902d0A29173Ba4B1', 'blockHash': HexBytes('0x9c5ed44fd2de9cd8a9b1666838e584b621315ff69324c2eec35aefd3404fa155'), 'blockNumber': 75})]

```

**Comment by schmir-at-bb** [comment]
We should probably fix that in the clientlib's end2end test first since this doesn't recognize the error, i.e. the tests do succeed. I've looked shortly over the clientlib code, but couldn't fix it.

**Comment by schmir-at-bb** [comment]
superseded by https://github.com/trustlines-protocol/clientlib/issues/280

also see https://github.com/trustlines-protocol/clientlib/pull/281
