### ISSUE TITLE
tl-relay cannot be started: "pysha3" distribution was not found

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/relay#418]
When installing the relay server with `pip install -c constraints.txt -e .` (i.e. in editable mode) into a fresh virtualenv, it cannot be started:

```
~/trustlines/protocol/relay (git)-[master] % tl-relay                           
Traceback (most recent call last):
  File "/home/bbralf/trustlines/venv/bin/tl-relay", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/bbralf/trustlines/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/home/bbralf/trustlines/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/home/bbralf/trustlines/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/bbralf/trustlines/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/bbralf/trustlines/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/bbralf/trustlines/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pysha3<2.0.0,>=1.0.0; extra == "pysha3"' distribution was not found and is required by eth-hash
```

With non-editable installs `tl-relay` can be started, but the following still does not work:
```
 >>> import pkg_resources
>>> pkg_resources.require("trustlines-relay")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bbralf/trustlines/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/bbralf/trustlines/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pysha3<2.0.0,>=1.0.0; extra == "pysha3"' distribution was not found and is required by eth-hash
```

**Comment by schmir-at-bb** [comment]
This can be reduced to:
```
$ pip install trustlines-contracts-deploy
$ python -c 'import pkg_resources; pkg_resources.require("trustlines-contracts-deploy")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bbralf/trustlines/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/bbralf/trustlines/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pysha3<2.0.0,>=1.0.0; extra == "pysha3"' distribution was not found and is required by eth-hash

```

**Comment by schmir-at-bb** [comment]
I think what's happening here is that pip fails to handle 'extras_require' dependencies of indirect dependencies. If you run
```
pip install -c constraints.txt contract-deploy-tools
pip install -c constraints.txt trustlines-contracts-deploy
```
everything is fine (please be aware that `contract-deploy-tools` is an indirect dependency of `trustlines-contracts-deploy`).

One workaround to solve this, would be to explicitly list those dependencies in contract-deploy-tools. From what I can tell we should however then pin dependencies on exact versions, because the extras-require dependency of `eth-tester[py-evm]` also does this. 

The setuptools docs explicitly mention that you should not do that, and as contract-deploy-tools can be used as a library, we should really refrain from doing so.

My suggestion now would be to pin the complete set of indirect and direct dependencies in the PyPI uploads that can be considered 'applications' (relay, ethindex, tlbc-monitor, bridge). That will give users a chance to just run `pip install trustlines-relay` and have a working version.

This is something that raiden already does for some time. They do this with the help of [pip tools](https://github.com/jazzband/pip-tools)

**Comment by berndbohmeier** [comment]
We now generate the requirements so you can no install the relay with 
```
pip install -r requirements.txt -e .
```
and it works

**Comment by berndbohmeier** [comment]
However, we do not pin the dependencies directly in the package yet.
