### ISSUE TITLE
Relay crashes on /mediation-fees endpoint

### ISSUE THREAD

**Issue by compojoom** [trustlines-protocol/relay#598]
The relay currently chokes on the /mediation-fees endpoint.

```
Traceback (most recent call last):
  File "/opt/relay/lib/python3.8/site-packages/flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
  File "/opt/relay/lib/python3.8/site-packages/werkzeug/routing.py", line 1799, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/relay/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/relay/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/relay/lib/python3.8/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/relay/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/relay/lib/python3.8/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/relay/lib/python3.8/site-packages/webargs/core.py", line 459, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/relay/lib/python3.8/site-packages/relay/api/resources.py", line 89, in dump_result
    return schema.dump(wrapped(*args, **kwargs))
  File "/opt/relay/lib/python3.8/site-packages/relay/api/resources.py", line 515, in get
    mediationFees = self.trustlines.get_earned_mediation_fees(
  File "/opt/relay/lib/python3.8/site-packages/relay/relay.py", line 319, in get_earned_mediation_fees
    return EventsInformationFetcher(
  File "/opt/relay/lib/python3.8/site-packages/relay/ethindex_db/events_informations.py", line 353, in get_earned_mediation_fees_in_between_timestamps
    mediation_fees = self.get_earned_mediation_fees(user_address, graph)
  File "/opt/relay/lib/python3.8/site-packages/relay/ethindex_db/events_informations.py", line 328, in get_earned_mediation_fees
    safety_checks_on_mediated_transfer_balance_updates(
  File "/opt/relay/lib/python3.8/site-packages/relay/ethindex_db/events_informations.py", line 570, in safety_checks_on_mediated_transfer_balance_updates
    assert False, "Found a mediated transfer with to/from not matching"
AssertionError: Found a mediated transfer with to/from not matching
```

At first look the problem seems to come from the currency network migration we did back in February. It seems that this somehow screws the event order.

**Comment by cducrest** [comment]
The problem comes from the algorithm here: https://github.com/trustlines-protocol/relay/blob/a91798dada5ae1adddb19af867e2f4d6b4999fda/src/relay/ethindex_db/events_informations.py#L279

We have a certain assumption as to how events are emitted by the currency network contract which did not hold for OwnedCurrencyNetwork contracts used during migration of CNs.
It has been fixed for the specific use case of CNs migrations, but I believe one could still forge a transaction that would make the relay server fail when getting the mediation. The user would need to make a certain aggregated transaction to corrupt the endpoint for his own address, so we can argue it is not important to solve.

The way to do that would be to call `applyInterests` https://github.com/trustlines-protocol/contracts/blob/master/contracts/currency-network/CurrencyNetworkBasic.sol#L226é twice within a transaction. This would create two consecutive balanceUpdate events that would trigger our signal for a mediated transfer. We can filter out some additional cases with requirements on the`from` and `to` fields of the `balanceUpdates`

We should probably rethink the algorithm if we want it to be super duper good.

**Comment by andfletcher** [comment]
done with #599 . potentially this was only a temp. fix and it might pop up in the future again.
